### ISSUE TITLE
mark_seen should definitely be False by default

### ISSUE THREAD

**Issue by jt-xx** [ikvk/imap_tools#179]
Hi,

I would expect that Mailbox.fetch() has no side effect by default.

https://github.com/ikvk/imap_tools/blob/0beffa346aa245f0cd2cfdcb538b0a6687bc193a/imap_tools/mailbox.py#L138

**Comment by axoroll7** [comment]
I do not agree. This library is high-level, I think things has to be simple by default.

**Comment by jt-xx** [comment]
Nowadays I'm finding it weird to have implicit side effects on a function call that's called "fetch".
But I understand that per RFC 3501 the \Seen flag is implicitly set.
RFC wins :)

**Comment by link2xt** [comment]
I can't think of a reason for using `BODY` fetch instead of `BODY.PEEK` for any IMAP user. If you fetch `BODY` and set `\Seen` flag implicitly, you may lose connection before you receive an answer and then the message is marked as `\Seen` and you have not actually received it and definitely not displayed or processed it. The only possible reason is that you don't particularly care about the seen flag, never read it yourself and just want to set it on every message eventually, but then you likely can simply never set it instead of always setting it.

This implicit setting of `\Seen` looks like a bad design of the initial protocol that was fixed by introducing a fixed version and naming it `BODY.PEEK` for backwards compatibility.

**Comment by ikvk** [comment]
1. There is `mark_seen = True, mark emails as seen on fetch` at docs
2. Legacy is often strange =)
