### ISSUE TITLE
Reading winmail.dat

### ISSUE THREAD

**Issue by Aset-21** [ikvk/imap_tools#195]
Good day. How do I read the winmail.dat attachment?

**Comment by ikvk** [comment]
Greetings. Seems that: https://github.com/koodaamo/tnefparse

--

If the sender sends a letter using Microsoft Outlook, Express, or Exchange (as well as a number of other less common third-party programs), some of the information in it may be transferred in an attachment called winmail.dat. On the net, you can see that this file is also called TNEF, which is an abbreviation for Transport Neutral Encapsulation Format.

The winmail.dat file occurs because the sender applied formatting in the application for sending the letter that is not supported by the program (for example, the browser) through which the recipient views this letter. At the same time, the letter from the sender was sent in RTF format. As a result, the recipient will find only the text and attached supported materials from the sent letter, and the formatting elements (font, color), vcf contact cards, icl calendar events and some other elements will be placed in a file called winmail.dat.
